platform :ios, '12.0'

target 'TestStorage' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestStorage
  pod 'KeychainAccess', '4.1.0'
  pod 'Sourcery', '0.17.0'

end
